### ISSUE TITLE
TypeError: 'DetailedResponse' object is not iterable

### ISSUE THREAD

**Issue by ayeshasa** [watson-developer-cloud/assistant-improve-recommendations-notebook#44]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-4e841c8f9938> in <module>
      7 
      8     # Store the workspace details in a dataframe
----> 9     df_workspace = json_normalize(workspace)
     10 
     11     # Get all intents present in current version of workspace

~/anaconda3/lib/python3.7/site-packages/pandas/io/json/normalize.py in json_normalize(data, record_path, meta, meta_prefix, record_prefix, errors, sep)
    200     if record_path is None:
    201         if any([isinstance(x, dict)
--> 202                 for x in compat.itervalues(y)] for y in data):
    203             # naive normalization, this is idempotent for flat records
    204             # and potentially will inflate the data considerably for

TypeError: 'DetailedResponse' object is not iterable

**Comment by zzhangncsu** [comment]
@ayeshasa This error seems to be caused by `watson-developer-cloud` version. Current code in this notebook works with `watson-developer-cloud>=1.0,<2.0`. You might have a version higher than or equal to 2.0.0. Could you please check which version you have installed in your environment. 

If you run the cell in Section 1.2, you should have the correct version installed. If the problem is still there, you can try replace the cell in section 1.2 with the following code to make sure a previous version is uninstalled.

```
# install watson-developer-cloud python SDK
# After running this cell once, comment out the following code. Packages only need to be installed once.
!pip3 uninstall -y "watson-developer-cloud"
!pip3 install --upgrade "watson-developer-cloud>=1.0,<2.0";

# Import required libraries
import pandas as pd
import matplotlib.pyplot as plt
import json
from pandas.io.json import json_normalize
from watson_developer_cloud import AssistantV1
import matplotlib.dates as mdates
import re
from IPython.display import display
```
