### ISSUE TITLE
Annotation File

### ISSUE THREAD

**Issue by DanielTresp** [watson-developer-cloud/assistant-improve-recommendations-notebook#47]
My question is how is the Annotation File made, because to retrieve a log is very much clear but for me to obtain this File is not, and I'm thinking in a manual way but if you guys can tell how would be great.

Thanks

**Comment by eric-wayne** [comment]
Hi @DanielTresp - Great question. The Measure Notebook, Section 9 includes this relevant text

> **Toward improving Effectiveness**
> 
> We suggest focusing on a group of problematic conversations, e.g., escalated conversations, then performing a deeper analysis on these conversation as follows.
> 

> 1.  Choose to download either the complete conversations (All.xlsx), or sampled escalated conversations Escalated_sample.xlsx, or non-escalated conversations NotEscalated_sample.xlsx.
> **2. Perform a manual assessment of these conversations.**
> 3.  Analyze the results using our Analyze Watson Assistant Effectiveness Jupyter Notebook.

But the instructions for this second step may not be apparent.   Let us give more explanation here, and we may need to add more detail to the documentation in the notebooks as well.

The Annotation file is completed as a manual step facilitated by the Measure Notebook and the Effectiveness Notebook.   The **IBM Watson Assistant Continuous Improvement Best Practices** document linked from https://github.com/watson-developer-cloud/assistant-improve-recommendations-notebook#introduction provides an overview of the manual assessment in the Analyze - Effectiveness section. 
Also, Section 9 of the Measure Notebook provides some general instructions. 

The manual assessment is done after creating a sampling file using the the Measure Notebook. After you complete the annotation, that file is the input to the Effectiveness Notebook.  The repo includes a sample completed Annotation file in https://github.com/watson-developer-cloud/assistant-improve-recommendations-notebook/tree/master/notebook/data, in the Annotation.xlsx file.
Notice the colors of the column headings.  The white columns are filled with data from the logs. You don't need to update those. The columns to the right of those columns (Columns V-AG in the sample) are questions that you need to fill in:  
- The first blue columns are basic questions about the response and a choice of the root cause of a problem, if the response was not correct or helpful.  
- The yellow columns are questions that you must answer related to the intents. 
- The light green columns are questions related to entities, 
- The last blue columns are questions related to dialog.  

So putting this together, one possible workflow:
1. Use the Measure Notebook to generate a sampling of logs. Section 6 will create three different alternative sampling Excel spreadsheets: All.xlsx, Escalated_sample.xlsx, NotEscalated_sample.xlsx.  Choose one of these spreadsheets to use as the starting point of your manual annotation file. The one you pick depends on what you want to focus on.  For example, if you want to focus on reducing escalations, you'd pick the Escalated_sample.xlsx.  If you want to sample a cross section of logs, use All.xlsx.
2. Using the sample Annotation.xlsx as a guide, update the spreadsheet you picked in step 1 by filling in the blank columns that correspond to the colored headings in the sample Annotation.xlsx spreadsheet.  If you are not the subject matter expert for your assistant, then you'll want to team up with one or more experts to do this.
3. After you've completed this annotation, you can use the Effectiveness Notebook to analyze the results.

Please advise if this is clear and if you have any other questions.

**Comment by DanielTresp** [comment]
Thank you so much for your great answer, I just thouhg that there was an automatic way to do it, but I realize that it might depend of how is built the assistant.

I just have a last question on the Try Out Panel you can see the top 3 intents, but on the logs that doesn´t appear or maybe I'm looking on the wrong spot, where can I get those?

**Comment by eric-wayne** [comment]
Yes, you need to pass `alternate_intents=true` when you call the /message API. Reference: https://cloud.ibm.com/apidocs/assistant/assistant-v2#send-user-input-to-assistant

If you pass this setting, it will cause more than just the top intent to be added to the logs.

**Comment by DanielTresp** [comment]
Thank you for your responses, those were super helpful.
